### ISSUE TITLE
openindiana/hipster box: broken rsync, wants a password

### ISSUE THREAD

**Issue by ThomasWaldmann** [OpenIndiana/vagrantfiles#8]
Maybe this is not the correct issue tracker, but I didn't find a better matching one.

The vagrant box is currently unusable for my `borgbackup` testing, because `rsync` wants a password (it should just work with the ssh key):

```
tw@server:~/w/borg$ vagrant box outdated
Checking if box 'openindiana/hipster' version '202409' is up to date...

tw@server:~/w/borg$ vagrant up openindiana
Bringing machine 'openindiana' up with 'virtualbox' provider...
==> openindiana: Importing base box 'openindiana/hipster'...
==> openindiana: Matching MAC address for NAT networking...
==> openindiana: Checking if box 'openindiana/hipster' version '202409' is up to date...
==> openindiana: Setting the name of the VM: borg_openindiana_1727730378317_44536
==> openindiana: Fixed port collision for 22 => 2222. Now on port 2202.
==> openindiana: Clearing any previously set network interfaces...
==> openindiana: Preparing network interfaces based on configuration...
    openindiana: Adapter 1: nat
==> openindiana: Forwarding ports...
    openindiana: 22 (guest) => 2202 (host) (adapter 1)
==> openindiana: Running 'pre-boot' VM customizations...
==> openindiana: Booting VM...
==> openindiana: Waiting for machine to boot. This may take a few minutes...
    openindiana: SSH address: 127.0.0.1:2202
    openindiana: SSH username: vagrant
    openindiana: SSH auth method: private key
    openindiana: 
    openindiana: Vagrant insecure key detected. Vagrant will automatically replace
    openindiana: this with a newly generated keypair for better security.
    openindiana: 

    openindiana: Inserting generated public key within guest...

    openindiana: Removing insecure key from the guest if it's present...
==> openindiana: Machine booted and ready!
==> openindiana: Checking for guest additions in VM...
==> openindiana: Rsyncing folder: /mnt/fastssd/tw/w/borg/ => /vagrant/borg/borg
(vagrant@127.0.0.1) Password: 
(vagrant@127.0.0.1) Password: 
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /mnt/fastssd/tw/w/borg/
Guest path: /vagrant/borg/borg
Command: "rsync" "--verbose" "--archive" "--delete" "--exclude" ".python-version" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2202 -o LogLevel=FATAL   -o ControlMaster=auto -o ControlPath=/tmp/vagrant-rsync-20240930-3856413-ahggoe -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/mnt/fastssd/tw/w/borg/.vagrant/machines/openindiana/virtualbox/private_key'" "--exclude" ".vagrant/" "/mnt/fastssd/tw/w/borg/" "vagrant@127.0.0.1:/vagrant/borg/borg"
Error: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
```

**Comment by ThomasWaldmann** [comment]
BTW, you could fill out that (maybe point to the correct github repo or give some contact info):

https://app.vagrantup.com/openindiana

**Comment by Toasterson** [comment]
> BTW, you could fill out that (maybe point to the correct github repo or give some contact info):
> 
> https://app.vagrantup.com/openindiana

Good point. Added links to the Issue tracker and Source repo to the box. Not much more I can add at the moment there but this should help guide people to the right place. 

In general if you don't find the place to open a Bug the Bug tracker is maintained. We have legacy tasks we couldn't find an agreement what to do with but new ones are responded to quickly.

Looks like the rsync setup changed since the last time I tested. I'll have a look to update/fix it.

**Comment by Toasterson** [comment]
Looks like this one is a bit deeper than with rsync. The Key setup I am making on the box works, but then vagrant generates new keys that do not work with our OpenSSH. There is a longer running analysis at the moment due to a problem with Encrypted Keys somehow. Fun side bug I found. I can have a box version with v202409 but vagrants `config.vm.box.version` only accepts semantic versioning... 

We have a version of OpenSSH in the works that fixes this, but it has other problems we need to hunt down.

**Comment by Toasterson** [comment]
We integrated the fix for that Issue but I am still testing and building the Vagrant box. Having to slot it in between lots of private time needed for family at the moment. Hope the next tries get some results.

**Comment by Toasterson** [comment]
And I managed to find all the issues with the box.
Turns out vagrant changed their file where they write the ssh_authorized key into a file named authorized_keys.temp I added that to the list of files to check and voila it works.

New Box release 2024.10 was added with simple semver number as to make version pinning in the vagrant file possible for later issues.

```
Vagrant.configure("2") do |config|
  config.vm.box = "openindiana/hipster"
  config.vm.box_version = "2024.10"
end
```

**Comment by ThomasWaldmann** [comment]
Thanks much! Will try the box ASAP for borgbackup testing.

**Comment by ThomasWaldmann** [comment]
Hmm, is there some networking or other severe issue?
```
Bringing machine 'openindiana' up with 'virtualbox' provider...
==> openindiana: Importing base box 'openindiana/hipster'...
==> openindiana: Matching MAC address for NAT networking...
==> openindiana: Checking if box 'openindiana/hipster' version '2024.10' is up to date...
==> openindiana: Setting the name of the VM: borg_openindiana_1730144193896_22613
==> openindiana: Fixed port collision for 22 => 2222. Now on port 2200.
==> openindiana: Clearing any previously set network interfaces...
==> openindiana: Preparing network interfaces based on configuration...
    openindiana: Adapter 1: nat
==> openindiana: Forwarding ports...
    openindiana: 22 (guest) => 2200 (host) (adapter 1)
==> openindiana: Running 'pre-boot' VM customizations...
==> openindiana: Booting VM...
==> openindiana: Waiting for machine to boot. This may take a few minutes...
    openindiana: SSH address: 127.0.0.1:2200
    openindiana: SSH username: vagrant
    openindiana: SSH auth method: private key
    openindiana: Warning: Connection reset. Retrying...
    openindiana: Warning: Remote connection disconnect. Retrying...
    openindiana: Warning: Connection reset. Retrying...
    openindiana: Warning: Remote connection disconnect. Retrying...
    openindiana: Warning: Connection reset. Retrying...
    openindiana: Warning: Remote connection disconnect. Retrying...
... (until it hits the timeout at 600 seconds)
    openindiana: Warning: Remote connection disconnect. Retrying...
    openindiana: Warning: Connection reset. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by Toasterson** [comment]
There where reports that vagrant has issues if more than one machine is running at the same time.

**Comment by ThomasWaldmann** [comment]
I frequently do tests with 4..8 machines in parallel - usually that works.

**Comment by Toasterson** [comment]
Do you have access to the console via Virtualbox? the root password is `vagrant` so if something gets stuck you can debug there. I had some timeouts trying to connect sometimes because the box took long too boot but no other sightings during testing. I will need some pointers to help debug

**Comment by ThomasWaldmann** [comment]
I'll have to reproduce on a local machine. I usually use a remote machine I have ssh access to, but I don't think I can access the VM VGA console there.

"vagrant status" says "running", but I can't connect to the sshd in the VM. So either it's not running or there is a network issue. The Vagrantfile is the same I used for a long time while the vagrant box was still working (and while there was that rsync issue).

**Comment by Toasterson** [comment]
It's ssh which went into maintenance mode. I got it repoduced locally. seems somehow the script messed up the sshd_config file when regenerating the box the second time.... Will fix now.

**Comment by ThomasWaldmann** [comment]
OK, locally tried it with virtualbox and a minimal Vagrantfile as shown on Vagrant cloud:

Network seems ok, but the sshd is not running. When trying to start sshd:

<img width="404" alt="Bildschirmfoto 2024-10-29 um 19 53 28" src="https://github.com/user-attachments/assets/9f2f34df-4686-4fff-a3bb-b82c1a0fdd6c">

That line has no configuration option, just these paths.

**Comment by Toasterson** [comment]
Yeah you are getting the same. Working on a fix for that. Seems the script got borked.

**Comment by Toasterson** [comment]
I tested a new fix for that and Updated the version.

**Comment by ThomasWaldmann** [comment]
It works! borgbackup platform tests running again on openindiana!
